DELETE http://localhost:3003/api/blogs/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2N2I1Y2M1MWU3NjljMTIzZWE2ZjM1NGEiLCJpYXQiOjE3Mzk5Njg4NDl9.tiuV20oIl581XLiwYqVq1fQEJxt7EssmL4EcXajg4eA
